// Copyright (c) 2015-2021 Daniel Cooke
// Use of this source code is governed by the MIT license that can be found in the LICENSE file.

#ifndef measures_fwd_hpp
#define measures_fwd_hpp

#include "core/csr/measures/measure.hpp"
#include "core/csr/measures/allele_depth.hpp"
#include "core/csr/measures/allele_frequency.hpp"
#include "core/csr/measures/allele_frequency_bias.hpp"
#include "core/csr/measures/depth.hpp"
#include "core/csr/measures/mapping_quality_divergence.hpp"
#include "core/csr/measures/mapping_quality_zero_count.hpp"
#include "core/csr/measures/mean_mapping_quality.hpp"
#include "core/csr/measures/model_posterior.hpp"
#include "core/csr/measures/model_posterior_by_depth.hpp"
#include "core/csr/measures/quality.hpp"
#include "core/csr/measures/quality_by_depth.hpp"
#include "core/csr/measures/genotype_quality.hpp"
#include "core/csr/measures/genotype_quality_by_depth.hpp"
#include "core/csr/measures/strand_bias.hpp"
#include "core/csr/measures/gc_content.hpp"
#include "core/csr/measures/filtered_read_fraction.hpp"
#include "core/csr/measures/clipped_read_fraction.hpp"
#include "core/csr/measures/is_denovo.hpp"
#include "core/csr/measures/is_somatic.hpp"
#include "core/csr/measures/ambiguous_read_fraction.hpp"
#include "core/csr/measures/median_base_quality.hpp"
#include "core/csr/measures/mismatch_count.hpp"
#include "core/csr/measures/mismatch_fraction.hpp"
#include "core/csr/measures/is_refcall.hpp"
#include "core/csr/measures/normal_contamination.hpp"
#include "core/csr/measures/denovo_contamination.hpp"
#include "core/csr/measures/read_side_bias.hpp"
#include "core/csr/measures/alt_allele_count.hpp"
#include "core/csr/measures/str_length.hpp"
#include "core/csr/measures/str_period.hpp"
#include "core/csr/measures/posterior_probability.hpp"
#include "core/csr/measures/posterior_probability_by_depth.hpp"
#include "core/csr/measures/classification_confidence.hpp"
#include "core/csr/measures/somatic_haplotype_count.hpp"
#include "core/csr/measures/median_somatic_mapping_quality.hpp"
#include "core/csr/measures/strand_disequilibrium.hpp"
#include "core/csr/measures/supplementary_fraction.hpp"
#include "core/csr/measures/misaligned_read_count.hpp"
#include "core/csr/measures/read_tail_bias.hpp"
#include "core/csr/measures/read_end_bias.hpp"
#include "core/csr/measures/variant_length.hpp"
#include "core/csr/measures/base_mismatch_count.hpp"
#include "core/csr/measures/base_mismatch_fraction.hpp"
#include "core/csr/measures/base_mismatch_quality.hpp"
#include "core/csr/measures/assigned_depth.hpp"
#include "core/csr/measures/duplicate_concordance.hpp"
#include "core/csr/measures/duplicate_allele_depth.hpp"
#include "core/csr/measures/duplicate_allele_fraction.hpp"
#include "core/csr/measures/error_rate.hpp"
#include "core/csr/measures/error_rate_stdev.hpp"
#include "core/csr/measures/is_transversion.hpp"
#include "core/csr/measures/phase_length.hpp"
#include "core/csr/measures/max_read_length.hpp"
#include "core/csr/measures/allele_mapping_quality.hpp"
#include "core/csr/measures/mean_likelihood.hpp"
#include "core/csr/measures/phylogeny_posterior.hpp"

#endif
